version: '3.8'

services:
  ollama:
    build: 
      context: ./ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: 
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - pdf_uploads:/app/uploads
      - vectorstore:/app/vectorstore
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  pdf_uploads:
  vectorstore: 